AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  VPCName:
    Type: String
Resources:
  Rds:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: shoghly
      DBName: shoghly
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSecurityGroups: 
        - !Ref RdsSecurityGroup

  Ec2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroups:
       - !Ref Ec2SecurityGroup
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install -g pm2
            sudo yum install -y gcc-c++ make
            curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
            sudo yum install -y nodejs
            sudo yum install -y git
            git clone https://github.com/mohamedelshamy9/shoghly.git
            cd ./shoghly
            touch .env
            sudo npm install
            sudo pm2 start index.js --watch

  S3:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: shoghly-s3

  Ec2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCName
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  RdsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCName
      GroupDescription: Enable access via MySQL port 3306
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

Outputs:
  DbEndpoint:
    Description: The connection endpoint for the database.
    Value: !GetAtt Rds.Endpoint.Address
  
  Ec2PublicDnsName:
    Description: The public DNS name of the specified instance.
    Value: !GetAtt Ec2.PublicDnsName
  
  Ec2PublicIp:
    Description: The public IP address of the specified instance.
    Value: !GetAtt Ec2.PublicIp
