version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ivj7e5epwk5p"
s3_prefix = "s3"
region = "eu-central-1"
profile = "ahmednmourad"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
