name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_DNS_NAME }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: cd shoghly/backend && npm install
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_DNS_NAME }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: cd shoghly/backend && git pull
